from selenium import webdriver
from time import sleep
from selenium.webdriver.support.select import Select

driver = webdriver.Chrome()
driver.maximize_window()

def test_add_product():
    driver.get('http://39.104.14.232/ecshop/wwwroot/admin/privilege.php?act=login')
    driver.find_element_by_name('username').send_keys('admin')
    driver.find_element_by_name('password').send_keys('123456')
    driver.find_element_by_xpath('/html/body/div/form/table/tbody/tr/td/table/tbody/tr[4]/td/input').click()
    driver.switch_to.frame('menu-frame')
    driver.find_element_by_xpath('//*[@id="menu-ul"]/li/ul/li[1]/a').click()
    driver.find_element_by_xpath('//*[@id="02_cat_and_goods"]/ul/li[1]/a').click()
    driver.switch_to.default_content()
    driver.switch_to.frame('main-frame')
    driver.find_element_by_xpath('/html/body/h1/span[1]/a').click()
    driver.find_element_by_name('goods_name').send_keys('测试商品wmx')
    sleep(1)
    driver.find_element_by_name('goods_sn').send_keys('19940310')
    sleep(1)
    driver.find_element_by_id('cat_name').send_keys('龙虾')
    sleep(1)
    Select(driver.find_element_by_name('other_cat[]')).select_by_value('420')
    sleep(1)
    # driver.find_element_by_id('brand_search')
    # driver.find_element_by_xpath('//*[@id="dishini迪士尼"]/a').click()
    # sleep(1)
    Select(driver.find_element_by_id('suppliers_id')).select_by_value('2')
    sleep(1)
    price = driver.find_element_by_name('shop_price').clear()
    sleep(1)
    price.send_keys('888')
    sleep(1)
    Pprice = driver.find_element_by_name('exclusive')
    Pprice.clear()
    sleep(1)
    Pprice.send_keys('808')
    sleep(1)
    Uprice = driver.find_element_by_id('rank_12')
    Uprice.clear()
    sleep(1)
    Uprice.send_keys('799')
    sleep(1)
    Gprice = driver.find_element_by_id('rank_15')
    Gprice.clear()
    sleep(1)
    Gprice.send_keys('779')
    sleep(1)
    Eprice = driver.find_element_by_id('rank_16')
    Eprice.clear()
    sleep(1)
    Eprice.send_keys('759')
    sleep(1)
    driver.find_element_by_xpath('//*[@id="tbody-volume"]/tbody/tr/td/a').click()
    sleep(1)
    driver.switch_to.alert.accept()
    sleep(1)
    driver.find_element_by_name('volume_number[]').send_keys('10')
    sleep(1)
    driver.find_element_by_name('volume_price[]').send_keys('800')
    sleep(1)
    marketprice = driver.find_element_by_name('market_price')
    marketprice.clear()
    sleep(1)
    marketprice.send_keys('1000')
    sleep(1)
    giveintegral = driver.find_element_by_name('give_integral')
    giveintegral.clear()
    sleep(1)
    giveintegral.send_keys('100')
    sleep(1)
    rankintegral = driver.find_element_by_name('rank_integral')
    rankintegral.clear()
    sleep(1)
    rankintegral.send_keys('100')
    sleep(1)
    driver.find_element_by_id('is_promote').click()
    sleep(1)
    promote = driver.find_element_by_name('promote_price')
    promote.clear()
    sleep(1)
    promote.send_keys('858')
    sleep(1)
    driver.find_element_by_id('is_buy').click()
    sleep(1)
    driver.find_element_by_id('buymax').send_keys('20')
    sleep(1)
    driver.find_element_by_id('selbtn3').click()
    sleep(1)
    driver.find_element_by_xpath('/html/body/div[7]/table/tbody/tr[2]/td[4]').click()
    sleep(1)
    driver.find_element_by_id('selbtn4').click()
    sleep(1)
    driver.find_element_by_xpath('/html/body/div[8]/table/tbody/tr[5]/td[4]').click()
    sleep(1)
    costprice = driver.find_element_by_name('cost_price')
    costprice.clear()
    sleep(1)
    costprice.send_keys('50')
    sleep(1)
    # driver.find_element_by_name('goods_img').send_keys('/Users/wangmingxia/Desktop/屏幕快照\ 2019-06-30\ 下午1.57.41.png ')
    # sleep(1)
    # driver.find_element_by_name('auto_thumb').click()
    # sleep(1)
    # driver.find_element_by_name('goods_thumb').send_keys('/Users/wangmingxia/Desktop/屏幕快照\ 2019-06-30\ 下午1.57.41.png ')
    # sleep(1)
    driver.find_element_by_name('is_catindex').click()
    sleep(1)
    driver.find_element_by_id('goods_info_submit').click()
    sleep(1)
    driver.quit()