from selenium import webdriver
from time import sleep
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.expected_conditions import presence_of_element_located as element_exist

options = webdriver.ChromeOptions()
options.add_argument('--disable-infobars') #添加参数
#options.add_argument('--headless')
options.add_argument('--start-maximized')
selenium = webdriver.Chrome(options=options)


def test_add_product(selenium):
    selenium.get('http://39.104.14.232/ecshop/wwwroot/admin/privilege.php?act=login')
    selenium.find_element_by_name('username').send_keys('admin')
    selenium.find_element_by_name('password').send_keys('123456')
    selenium.find_element_by_css_selector('input.button2').click()
    selenium.switch_to.frame('menu-frame')
    selenium.find_element_by_link_text('商品管理').click()
    sleep(1)
    selenium.find_element_by_link_text('商品列表').click()
    selenium.switch_to.default_content()
    selenium.switch_to.frame('main-frame')
    selenium.find_element_by_xpath('/html/body/h1/span[1]/a').click()
    selenium.find_element_by_name('goods_name').send_keys('测试商品wmx2')
    sleep(1)
    selenium.find_element_by_name('goods_sn').send_keys('199403102')
    sleep(1)
    selenium.find_element_by_id('cat_name').send_keys('龙虾')
    sleep(1)
    Select(selenium.find_element_by_name('other_cat[]')).select_by_value('420')
    sleep(1)
    Select(selenium.find_element_by_id('suppliers_id')).select_by_value('2')
    sleep(3)
    price = selenium.find_element_by_name('shop_price')
    price.clear()
    sleep(1)
    price.send_keys('888')
    sleep(1)
    Pprice = selenium.find_element_by_name('exclusive')
    Pprice.clear()
    sleep(1)
    Pprice.send_keys('808')
    sleep(1)
    Uprice = selenium.find_element_by_id('rank_12')
    Uprice.clear()
    sleep(1)
    Uprice.send_keys('799')
    sleep(1)
    Gprice = selenium.find_element_by_id('rank_15')
    Gprice.clear()
    sleep(1)
    Gprice.send_keys('779')
    sleep(1)
    Eprice = selenium.find_element_by_id('rank_16')
    Eprice.clear()
    sleep(1)
    Eprice.send_keys('759')
    sleep(1)
    selenium.find_element_by_xpath('//*[@id="tbody-volume"]/tbody/tr/td/a').click()
    sleep(1)
    selenium.switch_to.alert.accept()
    sleep(1)
    selenium.find_element_by_name('volume_number[]').send_keys('10')
    sleep(1)
    selenium.find_element_by_name('volume_price[]').send_keys('800')
    sleep(1)
    marketprice = selenium.find_element_by_name('market_price')
    marketprice.clear()
    sleep(1)
    marketprice.send_keys('1000')
    sleep(1)
    giveintegral = selenium.find_element_by_name('give_integral')
    giveintegral.clear()
    sleep(1)
    giveintegral.send_keys('100')
    sleep(1)
    rankintegral = selenium.find_element_by_name('rank_integral')
    rankintegral.clear()
    sleep(1)
    rankintegral.send_keys('100')
    sleep(1)
    selenium.find_element_by_id('is_promote').click()
    sleep(1)
    promote = selenium.find_element_by_name('promote_price')
    promote.clear()
    sleep(1)
    promote.send_keys('858')
    sleep(1)
    selenium.find_element_by_id('is_buy').click()
    sleep(1)
    selenium.find_element_by_id('buymax').send_keys('20')
    sleep(1)
    # selenium.find_element_by_id('selbtn3').click()
    # sleep(1)
    # selenium.find_element_by_xpath('/html/body/div[7]/table/tbody/tr[2]/td[4]').click()
    # sleep(1)
    # selenium.find_element_by_id('selbtn4').click()
    # sleep(1)
    # selenium.find_element_by_xpath('/html/body/div[8]/table/tbody/tr[5]/td[4]').click()
    # sleep(1)
    costprice = selenium.find_element_by_name('cost_price')
    costprice.clear()
    sleep(1)
    costprice.send_keys('50')
    sleep(1)
    selenium.find_element_by_name('is_catindex').click()
    sleep(1)
    selenium.find_element_by_id('goods_info_submit').click()
    sleep(1)
    assert element_exist(('link text', '添加新商品'))
    assert element_exist(('link text', '商品列表'))


def test_search_product(selenium):
    selenium.get('http://39.104.14.232/ecshop/wwwroot/admin/privilege.php?act=login')
    selenium.find_element_by_name('username').send_keys('admin')
    selenium.find_element_by_name('password').send_keys('123456')
    selenium.find_element_by_css_selector('input.button2').click()
    selenium.switch_to.frame('menu-frame')
    selenium.find_element_by_link_text('商品管理').click()
    sleep(1)
    selenium.find_element_by_link_text('商品列表').click()
    selenium.switch_to.default_content()
    selenium.switch_to.frame('main-frame')
    # driver.find_element_by_css_selector('input#cat_name').send_keys('龙虾')
    # sleep(1)
    # Select(driver.find_element_by_id('selYRU')).select_by_value('is_promote')
    # sleep(1)
    selenium.find_element_by_name('keyword').send_keys('wmx')
    sleep(1)
    selenium.find_element_by_css_selector('input.button').click()
    sleep(1)
    assert element_exist(('text', 'wmx'))

def test_add_product_class(selenium):
    selenium.get('http://39.104.14.232/ecshop/wwwroot/admin/privilege.php?act=login')
    selenium.find_element_by_name('username').send_keys('admin')
    selenium.find_element_by_name('password').send_keys('123456')
    selenium.find_element_by_css_selector('input.button2').click()
    selenium.switch_to.frame('menu-frame')
    selenium.find_element_by_link_text('商品管理').click()
    sleep(1)
    selenium.find_element_by_link_text('商品分类').click()
    selenium.switch_to.default_content()
    selenium.switch_to.frame('main-frame')
    selenium.find_element_by_link_text('添加分类').click()
    sleep(1)
    selenium.find_element_by_xpath('//textarea[@name="cat_name"]').send_keys('wmx的分类2')
    sleep(1)
    Select(selenium.find_element_by_xpath('//select["parent_id"]')).select_by_value('147')
    sleep(1)
    selenium.find_element_by_css_selector('[name=measure_unit]').send_keys('个')
    sleep(1)
    selenium.find_element_by_xpath('//input[@name="show_in_nav"][@value="1"]').click()
    sleep(1)
    selenium.find_element_by_xpath('//input[@name="cat_recommend[]"][@value="1"]').click()
    sleep(1)
    selenium.find_element_by_xpath('//*[@id="tbody-attr"]/tbody/tr/td/a').click()
    sleep(1)
    selenium.switch_to.alert.accept()
    sleep(1)
    Select(selenium.find_element_by_xpath('//*[@id="tbody-attr"]/tbody/tr/td/select[1]')).select_by_value('15')
    sleep(1)
    price_range = selenium.find_element_by_xpath('//input[@name="grade"]')
    price_range.clear()
    sleep(1)
    price_range.send_keys('2')
    sleep(1)
    selenium.find_element_by_css_selector('[name=keywords]').send_keys('wmx')
    sleep(1)
    selenium.find_element_by_css_selector('[name=cat_desc]').send_keys('社会主义爱国好少年')
    sleep(1)
    show = selenium.find_element_by_xpath('//input[@name="show_in_index"][@value="1"]')
    if show.is_selected() is False:
        show.click()
    sleep(1)
    selenium.find_element_by_xpath('//input[@name="show_goods_num"]').send_keys('5')
    selenium.find_element_by_xpath('//input[@class="button"][@value=" 确定 "]')
    sleep(1)
    assert element_exist(("link text", "继续添加商品分类"))

